services:
  web:
    build: .
    command: gunicorn wsgi:app --bind 0.0.0.0:5000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - opensearch
  scheduler:
    build: .
    command: python scheduler_app.py
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - opensearch
  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: gematria
      POSTGRES_USER: gematria
      POSTGRES_PASSWORD: gematria
    volumes:
      - pgdata:/var/lib/postgresql/data
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    environment:
      discovery.type: single-node
    ports:
      - '9200:9200'
    volumes:
      - osdata:/usr/share/opensearch/data
  
volumes:
  pgdata:
  osdata:
